/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClinicsRouteImport } from './routes/clinics'
import { Route as BusinessIntakeRouteImport } from './routes/business-intake'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripTokenRouteImport } from './routes/trip.$token'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ResourcesComparisonRouteImport } from './routes/resources.comparison'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ClinicsCityRouteImport } from './routes/clinics.$city'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated/trips'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated/training'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/superadmin'
import { Route as AuthenticatedScreeningRouteImport } from './routes/_authenticated/screening'
import { Route as AuthenticatedRentalsRouteImport } from './routes/_authenticated/rentals'
import { Route as AuthenticatedProviderRouteImport } from './routes/_authenticated/provider'
import { Route as AuthenticatedPrivilegesRouteImport } from './routes/_authenticated/privileges'
import { Route as AuthenticatedPatientRouteImport } from './routes/_authenticated/patient'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated/fleet'
import { Route as AuthenticatedDispatchRouteImport } from './routes/_authenticated/dispatch'
import { Route as AuthenticatedDeveloperRouteImport } from './routes/_authenticated/developer'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedCallCenterRouteImport } from './routes/_authenticated/call-center'
import { Route as AuthenticatedBusinessRouteImport } from './routes/_authenticated/business'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSuperadminApiDocsRouteImport } from './routes/_authenticated/superadmin.api-docs'
import { Route as ApiPublicV1Work_ordersRouteImport } from './routes/api/public/v1/work_orders'
import { Route as ApiPublicV1Web_intakeRouteImport } from './routes/api/public/v1/web_intake'
import { Route as ApiPublicV1StatsRouteImport } from './routes/api/public/v1/stats'
import { Route as ApiPublicV1Screening_ordersRouteImport } from './routes/api/public/v1/screening_orders'
import { Route as ApiPublicV1OpenapiRouteImport } from './routes/api/public/v1/openapi'
import { Route as ApiPublicV1IncidentsRouteImport } from './routes/api/public/v1/incidents'
import { Route as ApiPublicV1FleetRouteImport } from './routes/api/public/v1/fleet'
import { Route as ApiPublicV1EtaRouteImport } from './routes/api/public/v1/eta'
import { Route as ApiPublicV1CredentialsRouteImport } from './routes/api/public/v1/credentials'
import { Route as ApiPublicV1CoursesRouteImport } from './routes/api/public/v1/courses'
import { Route as ApiPublicV1ClinicsRouteImport } from './routes/api/public/v1/clinics'
import { Route as ApiPublicV1Business_intakeRouteImport } from './routes/api/public/v1/business_intake'
import { Route as ApiAdminV1TicketsRouteImport } from './routes/api/admin/v1/tickets'
import { Route as ApiAdminV1TenantSubscriptionsRouteImport } from './routes/api/admin/v1/tenant-subscriptions'
import { Route as ApiAdminV1SubscriptionsRouteImport } from './routes/api/admin/v1/subscriptions'
import { Route as ApiAdminV1SubscribersRouteImport } from './routes/api/admin/v1/subscribers'
import { Route as ApiAdminV1RolesRouteImport } from './routes/api/admin/v1/roles'
import { Route as ApiAdminV1PromotionsRouteImport } from './routes/api/admin/v1/promotions'
import { Route as ApiAdminV1PrivilegesRouteImport } from './routes/api/admin/v1/privileges'
import { Route as ApiAdminV1PlansRouteImport } from './routes/api/admin/v1/plans'
import { Route as ApiAdminV1PaymentsRouteImport } from './routes/api/admin/v1/payments'
import { Route as ApiAdminV1OpenapiRouteImport } from './routes/api/admin/v1/openapi'
import { Route as ApiAdminV1InvoicesRouteImport } from './routes/api/admin/v1/invoices'
import { Route as ApiAdminV1BusinessRequestsRouteImport } from './routes/api/admin/v1/business-requests'
import { Route as ApiAdminV1BugsRouteImport } from './routes/api/admin/v1/bugs'
import { Route as ApiAdminV1AuditRouteImport } from './routes/api/admin/v1/audit'
import { Route as ApiPublicV1ShareTokenRouteImport } from './routes/api/public/v1/share.$token'
import { Route as ApiPublicV1IncidentsIdRouteImport } from './routes/api/public/v1/incidents.$id'
import { Route as ApiPublicV1DebugEventsRouteImport } from './routes/api/public/v1/debug.events'
import { Route as ApiAdminV1UsageDailyRouteImport } from './routes/api/admin/v1/usage.daily'
import { Route as ApiAdminV1TenantSubscriptionsIdRouteImport } from './routes/api/admin/v1/tenant-subscriptions.$id'
import { Route as ApiAdminV1SubscribersIdRouteImport } from './routes/api/admin/v1/subscribers.$id'
import { Route as ApiAdminV1PlansIdRouteImport } from './routes/api/admin/v1/plans.$id'
import { Route as ApiAdminV1DiagnosticsSuperadminRouteImport } from './routes/api/admin/v1/diagnostics.superadmin'
import { Route as ApiAdminV1ConfigOverridesRouteImport } from './routes/api/admin/v1/config.overrides'
import { Route as ApiAdminV1ConfigBaseRouteImport } from './routes/api/admin/v1/config.base'
import { Route as ApiAdminV1BusinessRequestsIdRouteImport } from './routes/api/admin/v1/business-requests.$id'
import { Route as ApiAdminV1AnalyticsKpisRouteImport } from './routes/api/admin/v1/analytics.kpis'
import { Route as ApiPublicV1VehiclesIdWork_ordersRouteImport } from './routes/api/public/v1/vehicles.$id.work_orders'
import { Route as ApiPublicV1VehiclesIdDefectsRouteImport } from './routes/api/public/v1/vehicles.$id.defects'
import { Route as ApiPublicV1VehiclesIdCredentialsRouteImport } from './routes/api/public/v1/vehicles.$id.credentials'
import { Route as ApiPublicV1FleetIdLocationRouteImport } from './routes/api/public/v1/fleet.$id.location'
import { Route as ApiAdminV1TicketsIdEventsRouteImport } from './routes/api/admin/v1/tickets.$id.events'
import { Route as ApiAdminV1PaymentsIdValidateRouteImport } from './routes/api/admin/v1/payments.$id.validate'
import { Route as ApiAdminV1ConfigEffectiveSubscriberIdRouteImport } from './routes/api/admin/v1/config.effective.$subscriberId'
import { Route as ApiAdminV1BusinessRequestsIdConvertRouteImport } from './routes/api/admin/v1/business-requests.$id.convert'
import { Route as ApiAdminV1BusinessRequestsIdAdvanceRouteImport } from './routes/api/admin/v1/business-requests.$id.advance'

const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsRoute = ClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIntakeRoute = BusinessIntakeRouteImport.update({
  id: '/business-intake',
  path: '/business-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTokenRoute = TripTokenRouteImport.update({
  id: '/trip/$token',
  path: '/trip/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ResourcesComparisonRoute = ResourcesComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const ClinicsCityRoute = ClinicsCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => ClinicsRoute,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScreeningRoute = AuthenticatedScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRentalsRoute = AuthenticatedRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProviderRoute = AuthenticatedProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrivilegesRoute = AuthenticatedPrivilegesRouteImport.update({
  id: '/privileges',
  path: '/privileges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientRoute = AuthenticatedPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispatchRoute = AuthenticatedDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeveloperRoute = AuthenticatedDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallCenterRoute = AuthenticatedCallCenterRouteImport.update({
  id: '/call-center',
  path: '/call-center',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessRoute = AuthenticatedBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperadminApiDocsRoute =
  AuthenticatedSuperadminApiDocsRouteImport.update({
    id: '/api-docs',
    path: '/api-docs',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const ApiPublicV1Work_ordersRoute = ApiPublicV1Work_ordersRouteImport.update({
  id: '/api/public/v1/work_orders',
  path: '/api/public/v1/work_orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1Web_intakeRoute = ApiPublicV1Web_intakeRouteImport.update({
  id: '/api/public/v1/web_intake',
  path: '/api/public/v1/web_intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1StatsRoute = ApiPublicV1StatsRouteImport.update({
  id: '/api/public/v1/stats',
  path: '/api/public/v1/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1Screening_ordersRoute =
  ApiPublicV1Screening_ordersRouteImport.update({
    id: '/api/public/v1/screening_orders',
    path: '/api/public/v1/screening_orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1OpenapiRoute = ApiPublicV1OpenapiRouteImport.update({
  id: '/api/public/v1/openapi',
  path: '/api/public/v1/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1IncidentsRoute = ApiPublicV1IncidentsRouteImport.update({
  id: '/api/public/v1/incidents',
  path: '/api/public/v1/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1FleetRoute = ApiPublicV1FleetRouteImport.update({
  id: '/api/public/v1/fleet',
  path: '/api/public/v1/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1EtaRoute = ApiPublicV1EtaRouteImport.update({
  id: '/api/public/v1/eta',
  path: '/api/public/v1/eta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CredentialsRoute = ApiPublicV1CredentialsRouteImport.update({
  id: '/api/public/v1/credentials',
  path: '/api/public/v1/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CoursesRoute = ApiPublicV1CoursesRouteImport.update({
  id: '/api/public/v1/courses',
  path: '/api/public/v1/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ClinicsRoute = ApiPublicV1ClinicsRouteImport.update({
  id: '/api/public/v1/clinics',
  path: '/api/public/v1/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1Business_intakeRoute =
  ApiPublicV1Business_intakeRouteImport.update({
    id: '/api/public/v1/business_intake',
    path: '/api/public/v1/business_intake',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminV1TicketsRoute = ApiAdminV1TicketsRouteImport.update({
  id: '/api/admin/v1/tickets',
  path: '/api/admin/v1/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1TenantSubscriptionsRoute =
  ApiAdminV1TenantSubscriptionsRouteImport.update({
    id: '/api/admin/v1/tenant-subscriptions',
    path: '/api/admin/v1/tenant-subscriptions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminV1SubscriptionsRoute = ApiAdminV1SubscriptionsRouteImport.update({
  id: '/api/admin/v1/subscriptions',
  path: '/api/admin/v1/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1SubscribersRoute = ApiAdminV1SubscribersRouteImport.update({
  id: '/api/admin/v1/subscribers',
  path: '/api/admin/v1/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1RolesRoute = ApiAdminV1RolesRouteImport.update({
  id: '/api/admin/v1/roles',
  path: '/api/admin/v1/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1PromotionsRoute = ApiAdminV1PromotionsRouteImport.update({
  id: '/api/admin/v1/promotions',
  path: '/api/admin/v1/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1PrivilegesRoute = ApiAdminV1PrivilegesRouteImport.update({
  id: '/api/admin/v1/privileges',
  path: '/api/admin/v1/privileges',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1PlansRoute = ApiAdminV1PlansRouteImport.update({
  id: '/api/admin/v1/plans',
  path: '/api/admin/v1/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1PaymentsRoute = ApiAdminV1PaymentsRouteImport.update({
  id: '/api/admin/v1/payments',
  path: '/api/admin/v1/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1OpenapiRoute = ApiAdminV1OpenapiRouteImport.update({
  id: '/api/admin/v1/openapi',
  path: '/api/admin/v1/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1InvoicesRoute = ApiAdminV1InvoicesRouteImport.update({
  id: '/api/admin/v1/invoices',
  path: '/api/admin/v1/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1BusinessRequestsRoute =
  ApiAdminV1BusinessRequestsRouteImport.update({
    id: '/api/admin/v1/business-requests',
    path: '/api/admin/v1/business-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminV1BugsRoute = ApiAdminV1BugsRouteImport.update({
  id: '/api/admin/v1/bugs',
  path: '/api/admin/v1/bugs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1AuditRoute = ApiAdminV1AuditRouteImport.update({
  id: '/api/admin/v1/audit',
  path: '/api/admin/v1/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ShareTokenRoute = ApiPublicV1ShareTokenRouteImport.update({
  id: '/api/public/v1/share/$token',
  path: '/api/public/v1/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1IncidentsIdRoute = ApiPublicV1IncidentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1IncidentsRoute,
} as any)
const ApiPublicV1DebugEventsRoute = ApiPublicV1DebugEventsRouteImport.update({
  id: '/api/public/v1/debug/events',
  path: '/api/public/v1/debug/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1UsageDailyRoute = ApiAdminV1UsageDailyRouteImport.update({
  id: '/api/admin/v1/usage/daily',
  path: '/api/admin/v1/usage/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1TenantSubscriptionsIdRoute =
  ApiAdminV1TenantSubscriptionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiAdminV1TenantSubscriptionsRoute,
  } as any)
const ApiAdminV1SubscribersIdRoute = ApiAdminV1SubscribersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminV1SubscribersRoute,
} as any)
const ApiAdminV1PlansIdRoute = ApiAdminV1PlansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminV1PlansRoute,
} as any)
const ApiAdminV1DiagnosticsSuperadminRoute =
  ApiAdminV1DiagnosticsSuperadminRouteImport.update({
    id: '/api/admin/v1/diagnostics/superadmin',
    path: '/api/admin/v1/diagnostics/superadmin',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminV1ConfigOverridesRoute =
  ApiAdminV1ConfigOverridesRouteImport.update({
    id: '/api/admin/v1/config/overrides',
    path: '/api/admin/v1/config/overrides',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminV1ConfigBaseRoute = ApiAdminV1ConfigBaseRouteImport.update({
  id: '/api/admin/v1/config/base',
  path: '/api/admin/v1/config/base',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminV1BusinessRequestsIdRoute =
  ApiAdminV1BusinessRequestsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiAdminV1BusinessRequestsRoute,
  } as any)
const ApiAdminV1AnalyticsKpisRoute = ApiAdminV1AnalyticsKpisRouteImport.update({
  id: '/api/admin/v1/analytics/kpis',
  path: '/api/admin/v1/analytics/kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1VehiclesIdWork_ordersRoute =
  ApiPublicV1VehiclesIdWork_ordersRouteImport.update({
    id: '/api/public/v1/vehicles/$id/work_orders',
    path: '/api/public/v1/vehicles/$id/work_orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1VehiclesIdDefectsRoute =
  ApiPublicV1VehiclesIdDefectsRouteImport.update({
    id: '/api/public/v1/vehicles/$id/defects',
    path: '/api/public/v1/vehicles/$id/defects',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1VehiclesIdCredentialsRoute =
  ApiPublicV1VehiclesIdCredentialsRouteImport.update({
    id: '/api/public/v1/vehicles/$id/credentials',
    path: '/api/public/v1/vehicles/$id/credentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1FleetIdLocationRoute =
  ApiPublicV1FleetIdLocationRouteImport.update({
    id: '/$id/location',
    path: '/$id/location',
    getParentRoute: () => ApiPublicV1FleetRoute,
  } as any)
const ApiAdminV1TicketsIdEventsRoute =
  ApiAdminV1TicketsIdEventsRouteImport.update({
    id: '/$id/events',
    path: '/$id/events',
    getParentRoute: () => ApiAdminV1TicketsRoute,
  } as any)
const ApiAdminV1PaymentsIdValidateRoute =
  ApiAdminV1PaymentsIdValidateRouteImport.update({
    id: '/$id/validate',
    path: '/$id/validate',
    getParentRoute: () => ApiAdminV1PaymentsRoute,
  } as any)
const ApiAdminV1ConfigEffectiveSubscriberIdRoute =
  ApiAdminV1ConfigEffectiveSubscriberIdRouteImport.update({
    id: '/api/admin/v1/config/effective/$subscriberId',
    path: '/api/admin/v1/config/effective/$subscriberId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminV1BusinessRequestsIdConvertRoute =
  ApiAdminV1BusinessRequestsIdConvertRouteImport.update({
    id: '/convert',
    path: '/convert',
    getParentRoute: () => ApiAdminV1BusinessRequestsIdRoute,
  } as any)
const ApiAdminV1BusinessRequestsIdAdvanceRoute =
  ApiAdminV1BusinessRequestsIdAdvanceRouteImport.update({
    id: '/advance',
    path: '/advance',
    getParentRoute: () => ApiAdminV1BusinessRequestsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/api-reference': typeof ApiReferenceRoute
  '/auth': typeof AuthRoute
  '/business-intake': typeof BusinessIntakeRoute
  '/clinics': typeof ClinicsRouteWithChildren
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/developers': typeof DevelopersRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/website': typeof WebsiteRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/call-center': typeof AuthenticatedCallCenterRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/dispatch': typeof AuthenticatedDispatchRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/patient': typeof AuthenticatedPatientRoute
  '/privileges': typeof AuthenticatedPrivilegesRoute
  '/provider': typeof AuthenticatedProviderRoute
  '/rentals': typeof AuthenticatedRentalsRoute
  '/screening': typeof AuthenticatedScreeningRoute
  '/superadmin': typeof AuthenticatedSuperadminRouteWithChildren
  '/training': typeof AuthenticatedTrainingRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/clinics/$city': typeof ClinicsCityRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/comparison': typeof ResourcesComparisonRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/trip/$token': typeof TripTokenRoute
  '/superadmin/api-docs': typeof AuthenticatedSuperadminApiDocsRoute
  '/api/admin/v1/audit': typeof ApiAdminV1AuditRoute
  '/api/admin/v1/bugs': typeof ApiAdminV1BugsRoute
  '/api/admin/v1/business-requests': typeof ApiAdminV1BusinessRequestsRouteWithChildren
  '/api/admin/v1/invoices': typeof ApiAdminV1InvoicesRoute
  '/api/admin/v1/openapi': typeof ApiAdminV1OpenapiRoute
  '/api/admin/v1/payments': typeof ApiAdminV1PaymentsRouteWithChildren
  '/api/admin/v1/plans': typeof ApiAdminV1PlansRouteWithChildren
  '/api/admin/v1/privileges': typeof ApiAdminV1PrivilegesRoute
  '/api/admin/v1/promotions': typeof ApiAdminV1PromotionsRoute
  '/api/admin/v1/roles': typeof ApiAdminV1RolesRoute
  '/api/admin/v1/subscribers': typeof ApiAdminV1SubscribersRouteWithChildren
  '/api/admin/v1/subscriptions': typeof ApiAdminV1SubscriptionsRoute
  '/api/admin/v1/tenant-subscriptions': typeof ApiAdminV1TenantSubscriptionsRouteWithChildren
  '/api/admin/v1/tickets': typeof ApiAdminV1TicketsRouteWithChildren
  '/api/public/v1/business_intake': typeof ApiPublicV1Business_intakeRoute
  '/api/public/v1/clinics': typeof ApiPublicV1ClinicsRoute
  '/api/public/v1/courses': typeof ApiPublicV1CoursesRoute
  '/api/public/v1/credentials': typeof ApiPublicV1CredentialsRoute
  '/api/public/v1/eta': typeof ApiPublicV1EtaRoute
  '/api/public/v1/fleet': typeof ApiPublicV1FleetRouteWithChildren
  '/api/public/v1/incidents': typeof ApiPublicV1IncidentsRouteWithChildren
  '/api/public/v1/openapi': typeof ApiPublicV1OpenapiRoute
  '/api/public/v1/screening_orders': typeof ApiPublicV1Screening_ordersRoute
  '/api/public/v1/stats': typeof ApiPublicV1StatsRoute
  '/api/public/v1/web_intake': typeof ApiPublicV1Web_intakeRoute
  '/api/public/v1/work_orders': typeof ApiPublicV1Work_ordersRoute
  '/api/admin/v1/analytics/kpis': typeof ApiAdminV1AnalyticsKpisRoute
  '/api/admin/v1/business-requests/$id': typeof ApiAdminV1BusinessRequestsIdRouteWithChildren
  '/api/admin/v1/config/base': typeof ApiAdminV1ConfigBaseRoute
  '/api/admin/v1/config/overrides': typeof ApiAdminV1ConfigOverridesRoute
  '/api/admin/v1/diagnostics/superadmin': typeof ApiAdminV1DiagnosticsSuperadminRoute
  '/api/admin/v1/plans/$id': typeof ApiAdminV1PlansIdRoute
  '/api/admin/v1/subscribers/$id': typeof ApiAdminV1SubscribersIdRoute
  '/api/admin/v1/tenant-subscriptions/$id': typeof ApiAdminV1TenantSubscriptionsIdRoute
  '/api/admin/v1/usage/daily': typeof ApiAdminV1UsageDailyRoute
  '/api/public/v1/debug/events': typeof ApiPublicV1DebugEventsRoute
  '/api/public/v1/incidents/$id': typeof ApiPublicV1IncidentsIdRoute
  '/api/public/v1/share/$token': typeof ApiPublicV1ShareTokenRoute
  '/api/admin/v1/business-requests/$id/advance': typeof ApiAdminV1BusinessRequestsIdAdvanceRoute
  '/api/admin/v1/business-requests/$id/convert': typeof ApiAdminV1BusinessRequestsIdConvertRoute
  '/api/admin/v1/config/effective/$subscriberId': typeof ApiAdminV1ConfigEffectiveSubscriberIdRoute
  '/api/admin/v1/payments/$id/validate': typeof ApiAdminV1PaymentsIdValidateRoute
  '/api/admin/v1/tickets/$id/events': typeof ApiAdminV1TicketsIdEventsRoute
  '/api/public/v1/fleet/$id/location': typeof ApiPublicV1FleetIdLocationRoute
  '/api/public/v1/vehicles/$id/credentials': typeof ApiPublicV1VehiclesIdCredentialsRoute
  '/api/public/v1/vehicles/$id/defects': typeof ApiPublicV1VehiclesIdDefectsRoute
  '/api/public/v1/vehicles/$id/work_orders': typeof ApiPublicV1VehiclesIdWork_ordersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/api-reference': typeof ApiReferenceRoute
  '/auth': typeof AuthRoute
  '/business-intake': typeof BusinessIntakeRoute
  '/clinics': typeof ClinicsRouteWithChildren
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/developers': typeof DevelopersRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/website': typeof WebsiteRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/call-center': typeof AuthenticatedCallCenterRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/dispatch': typeof AuthenticatedDispatchRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/patient': typeof AuthenticatedPatientRoute
  '/privileges': typeof AuthenticatedPrivilegesRoute
  '/provider': typeof AuthenticatedProviderRoute
  '/rentals': typeof AuthenticatedRentalsRoute
  '/screening': typeof AuthenticatedScreeningRoute
  '/superadmin': typeof AuthenticatedSuperadminRouteWithChildren
  '/training': typeof AuthenticatedTrainingRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/clinics/$city': typeof ClinicsCityRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/comparison': typeof ResourcesComparisonRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/trip/$token': typeof TripTokenRoute
  '/superadmin/api-docs': typeof AuthenticatedSuperadminApiDocsRoute
  '/api/admin/v1/audit': typeof ApiAdminV1AuditRoute
  '/api/admin/v1/bugs': typeof ApiAdminV1BugsRoute
  '/api/admin/v1/business-requests': typeof ApiAdminV1BusinessRequestsRouteWithChildren
  '/api/admin/v1/invoices': typeof ApiAdminV1InvoicesRoute
  '/api/admin/v1/openapi': typeof ApiAdminV1OpenapiRoute
  '/api/admin/v1/payments': typeof ApiAdminV1PaymentsRouteWithChildren
  '/api/admin/v1/plans': typeof ApiAdminV1PlansRouteWithChildren
  '/api/admin/v1/privileges': typeof ApiAdminV1PrivilegesRoute
  '/api/admin/v1/promotions': typeof ApiAdminV1PromotionsRoute
  '/api/admin/v1/roles': typeof ApiAdminV1RolesRoute
  '/api/admin/v1/subscribers': typeof ApiAdminV1SubscribersRouteWithChildren
  '/api/admin/v1/subscriptions': typeof ApiAdminV1SubscriptionsRoute
  '/api/admin/v1/tenant-subscriptions': typeof ApiAdminV1TenantSubscriptionsRouteWithChildren
  '/api/admin/v1/tickets': typeof ApiAdminV1TicketsRouteWithChildren
  '/api/public/v1/business_intake': typeof ApiPublicV1Business_intakeRoute
  '/api/public/v1/clinics': typeof ApiPublicV1ClinicsRoute
  '/api/public/v1/courses': typeof ApiPublicV1CoursesRoute
  '/api/public/v1/credentials': typeof ApiPublicV1CredentialsRoute
  '/api/public/v1/eta': typeof ApiPublicV1EtaRoute
  '/api/public/v1/fleet': typeof ApiPublicV1FleetRouteWithChildren
  '/api/public/v1/incidents': typeof ApiPublicV1IncidentsRouteWithChildren
  '/api/public/v1/openapi': typeof ApiPublicV1OpenapiRoute
  '/api/public/v1/screening_orders': typeof ApiPublicV1Screening_ordersRoute
  '/api/public/v1/stats': typeof ApiPublicV1StatsRoute
  '/api/public/v1/web_intake': typeof ApiPublicV1Web_intakeRoute
  '/api/public/v1/work_orders': typeof ApiPublicV1Work_ordersRoute
  '/api/admin/v1/analytics/kpis': typeof ApiAdminV1AnalyticsKpisRoute
  '/api/admin/v1/business-requests/$id': typeof ApiAdminV1BusinessRequestsIdRouteWithChildren
  '/api/admin/v1/config/base': typeof ApiAdminV1ConfigBaseRoute
  '/api/admin/v1/config/overrides': typeof ApiAdminV1ConfigOverridesRoute
  '/api/admin/v1/diagnostics/superadmin': typeof ApiAdminV1DiagnosticsSuperadminRoute
  '/api/admin/v1/plans/$id': typeof ApiAdminV1PlansIdRoute
  '/api/admin/v1/subscribers/$id': typeof ApiAdminV1SubscribersIdRoute
  '/api/admin/v1/tenant-subscriptions/$id': typeof ApiAdminV1TenantSubscriptionsIdRoute
  '/api/admin/v1/usage/daily': typeof ApiAdminV1UsageDailyRoute
  '/api/public/v1/debug/events': typeof ApiPublicV1DebugEventsRoute
  '/api/public/v1/incidents/$id': typeof ApiPublicV1IncidentsIdRoute
  '/api/public/v1/share/$token': typeof ApiPublicV1ShareTokenRoute
  '/api/admin/v1/business-requests/$id/advance': typeof ApiAdminV1BusinessRequestsIdAdvanceRoute
  '/api/admin/v1/business-requests/$id/convert': typeof ApiAdminV1BusinessRequestsIdConvertRoute
  '/api/admin/v1/config/effective/$subscriberId': typeof ApiAdminV1ConfigEffectiveSubscriberIdRoute
  '/api/admin/v1/payments/$id/validate': typeof ApiAdminV1PaymentsIdValidateRoute
  '/api/admin/v1/tickets/$id/events': typeof ApiAdminV1TicketsIdEventsRoute
  '/api/public/v1/fleet/$id/location': typeof ApiPublicV1FleetIdLocationRoute
  '/api/public/v1/vehicles/$id/credentials': typeof ApiPublicV1VehiclesIdCredentialsRoute
  '/api/public/v1/vehicles/$id/defects': typeof ApiPublicV1VehiclesIdDefectsRoute
  '/api/public/v1/vehicles/$id/work_orders': typeof ApiPublicV1VehiclesIdWork_ordersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/api-reference': typeof ApiReferenceRoute
  '/auth': typeof AuthRoute
  '/business-intake': typeof BusinessIntakeRoute
  '/clinics': typeof ClinicsRouteWithChildren
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/developers': typeof DevelopersRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/website': typeof WebsiteRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/business': typeof AuthenticatedBusinessRoute
  '/_authenticated/call-center': typeof AuthenticatedCallCenterRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/developer': typeof AuthenticatedDeveloperRoute
  '/_authenticated/dispatch': typeof AuthenticatedDispatchRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRoute
  '/_authenticated/patient': typeof AuthenticatedPatientRoute
  '/_authenticated/privileges': typeof AuthenticatedPrivilegesRoute
  '/_authenticated/provider': typeof AuthenticatedProviderRoute
  '/_authenticated/rentals': typeof AuthenticatedRentalsRoute
  '/_authenticated/screening': typeof AuthenticatedScreeningRoute
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRouteWithChildren
  '/_authenticated/training': typeof AuthenticatedTrainingRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRoute
  '/clinics/$city': typeof ClinicsCityRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/resources/comparison': typeof ResourcesComparisonRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/trip/$token': typeof TripTokenRoute
  '/_authenticated/superadmin/api-docs': typeof AuthenticatedSuperadminApiDocsRoute
  '/api/admin/v1/audit': typeof ApiAdminV1AuditRoute
  '/api/admin/v1/bugs': typeof ApiAdminV1BugsRoute
  '/api/admin/v1/business-requests': typeof ApiAdminV1BusinessRequestsRouteWithChildren
  '/api/admin/v1/invoices': typeof ApiAdminV1InvoicesRoute
  '/api/admin/v1/openapi': typeof ApiAdminV1OpenapiRoute
  '/api/admin/v1/payments': typeof ApiAdminV1PaymentsRouteWithChildren
  '/api/admin/v1/plans': typeof ApiAdminV1PlansRouteWithChildren
  '/api/admin/v1/privileges': typeof ApiAdminV1PrivilegesRoute
  '/api/admin/v1/promotions': typeof ApiAdminV1PromotionsRoute
  '/api/admin/v1/roles': typeof ApiAdminV1RolesRoute
  '/api/admin/v1/subscribers': typeof ApiAdminV1SubscribersRouteWithChildren
  '/api/admin/v1/subscriptions': typeof ApiAdminV1SubscriptionsRoute
  '/api/admin/v1/tenant-subscriptions': typeof ApiAdminV1TenantSubscriptionsRouteWithChildren
  '/api/admin/v1/tickets': typeof ApiAdminV1TicketsRouteWithChildren
  '/api/public/v1/business_intake': typeof ApiPublicV1Business_intakeRoute
  '/api/public/v1/clinics': typeof ApiPublicV1ClinicsRoute
  '/api/public/v1/courses': typeof ApiPublicV1CoursesRoute
  '/api/public/v1/credentials': typeof ApiPublicV1CredentialsRoute
  '/api/public/v1/eta': typeof ApiPublicV1EtaRoute
  '/api/public/v1/fleet': typeof ApiPublicV1FleetRouteWithChildren
  '/api/public/v1/incidents': typeof ApiPublicV1IncidentsRouteWithChildren
  '/api/public/v1/openapi': typeof ApiPublicV1OpenapiRoute
  '/api/public/v1/screening_orders': typeof ApiPublicV1Screening_ordersRoute
  '/api/public/v1/stats': typeof ApiPublicV1StatsRoute
  '/api/public/v1/web_intake': typeof ApiPublicV1Web_intakeRoute
  '/api/public/v1/work_orders': typeof ApiPublicV1Work_ordersRoute
  '/api/admin/v1/analytics/kpis': typeof ApiAdminV1AnalyticsKpisRoute
  '/api/admin/v1/business-requests/$id': typeof ApiAdminV1BusinessRequestsIdRouteWithChildren
  '/api/admin/v1/config/base': typeof ApiAdminV1ConfigBaseRoute
  '/api/admin/v1/config/overrides': typeof ApiAdminV1ConfigOverridesRoute
  '/api/admin/v1/diagnostics/superadmin': typeof ApiAdminV1DiagnosticsSuperadminRoute
  '/api/admin/v1/plans/$id': typeof ApiAdminV1PlansIdRoute
  '/api/admin/v1/subscribers/$id': typeof ApiAdminV1SubscribersIdRoute
  '/api/admin/v1/tenant-subscriptions/$id': typeof ApiAdminV1TenantSubscriptionsIdRoute
  '/api/admin/v1/usage/daily': typeof ApiAdminV1UsageDailyRoute
  '/api/public/v1/debug/events': typeof ApiPublicV1DebugEventsRoute
  '/api/public/v1/incidents/$id': typeof ApiPublicV1IncidentsIdRoute
  '/api/public/v1/share/$token': typeof ApiPublicV1ShareTokenRoute
  '/api/admin/v1/business-requests/$id/advance': typeof ApiAdminV1BusinessRequestsIdAdvanceRoute
  '/api/admin/v1/business-requests/$id/convert': typeof ApiAdminV1BusinessRequestsIdConvertRoute
  '/api/admin/v1/config/effective/$subscriberId': typeof ApiAdminV1ConfigEffectiveSubscriberIdRoute
  '/api/admin/v1/payments/$id/validate': typeof ApiAdminV1PaymentsIdValidateRoute
  '/api/admin/v1/tickets/$id/events': typeof ApiAdminV1TicketsIdEventsRoute
  '/api/public/v1/fleet/$id/location': typeof ApiPublicV1FleetIdLocationRoute
  '/api/public/v1/vehicles/$id/credentials': typeof ApiPublicV1VehiclesIdCredentialsRoute
  '/api/public/v1/vehicles/$id/defects': typeof ApiPublicV1VehiclesIdDefectsRoute
  '/api/public/v1/vehicles/$id/work_orders': typeof ApiPublicV1VehiclesIdWork_ordersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-docs'
    | '/api-reference'
    | '/auth'
    | '/business-intake'
    | '/clinics'
    | '/contact'
    | '/demo'
    | '/developers'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/website'
    | '/admin'
    | '/audit'
    | '/business'
    | '/call-center'
    | '/compliance'
    | '/developer'
    | '/dispatch'
    | '/fleet'
    | '/patient'
    | '/privileges'
    | '/provider'
    | '/rentals'
    | '/screening'
    | '/superadmin'
    | '/training'
    | '/trips'
    | '/clinics/$city'
    | '/resources/$slug'
    | '/resources/comparison'
    | '/services/$slug'
    | '/trip/$token'
    | '/superadmin/api-docs'
    | '/api/admin/v1/audit'
    | '/api/admin/v1/bugs'
    | '/api/admin/v1/business-requests'
    | '/api/admin/v1/invoices'
    | '/api/admin/v1/openapi'
    | '/api/admin/v1/payments'
    | '/api/admin/v1/plans'
    | '/api/admin/v1/privileges'
    | '/api/admin/v1/promotions'
    | '/api/admin/v1/roles'
    | '/api/admin/v1/subscribers'
    | '/api/admin/v1/subscriptions'
    | '/api/admin/v1/tenant-subscriptions'
    | '/api/admin/v1/tickets'
    | '/api/public/v1/business_intake'
    | '/api/public/v1/clinics'
    | '/api/public/v1/courses'
    | '/api/public/v1/credentials'
    | '/api/public/v1/eta'
    | '/api/public/v1/fleet'
    | '/api/public/v1/incidents'
    | '/api/public/v1/openapi'
    | '/api/public/v1/screening_orders'
    | '/api/public/v1/stats'
    | '/api/public/v1/web_intake'
    | '/api/public/v1/work_orders'
    | '/api/admin/v1/analytics/kpis'
    | '/api/admin/v1/business-requests/$id'
    | '/api/admin/v1/config/base'
    | '/api/admin/v1/config/overrides'
    | '/api/admin/v1/diagnostics/superadmin'
    | '/api/admin/v1/plans/$id'
    | '/api/admin/v1/subscribers/$id'
    | '/api/admin/v1/tenant-subscriptions/$id'
    | '/api/admin/v1/usage/daily'
    | '/api/public/v1/debug/events'
    | '/api/public/v1/incidents/$id'
    | '/api/public/v1/share/$token'
    | '/api/admin/v1/business-requests/$id/advance'
    | '/api/admin/v1/business-requests/$id/convert'
    | '/api/admin/v1/config/effective/$subscriberId'
    | '/api/admin/v1/payments/$id/validate'
    | '/api/admin/v1/tickets/$id/events'
    | '/api/public/v1/fleet/$id/location'
    | '/api/public/v1/vehicles/$id/credentials'
    | '/api/public/v1/vehicles/$id/defects'
    | '/api/public/v1/vehicles/$id/work_orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-docs'
    | '/api-reference'
    | '/auth'
    | '/business-intake'
    | '/clinics'
    | '/contact'
    | '/demo'
    | '/developers'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/website'
    | '/admin'
    | '/audit'
    | '/business'
    | '/call-center'
    | '/compliance'
    | '/developer'
    | '/dispatch'
    | '/fleet'
    | '/patient'
    | '/privileges'
    | '/provider'
    | '/rentals'
    | '/screening'
    | '/superadmin'
    | '/training'
    | '/trips'
    | '/clinics/$city'
    | '/resources/$slug'
    | '/resources/comparison'
    | '/services/$slug'
    | '/trip/$token'
    | '/superadmin/api-docs'
    | '/api/admin/v1/audit'
    | '/api/admin/v1/bugs'
    | '/api/admin/v1/business-requests'
    | '/api/admin/v1/invoices'
    | '/api/admin/v1/openapi'
    | '/api/admin/v1/payments'
    | '/api/admin/v1/plans'
    | '/api/admin/v1/privileges'
    | '/api/admin/v1/promotions'
    | '/api/admin/v1/roles'
    | '/api/admin/v1/subscribers'
    | '/api/admin/v1/subscriptions'
    | '/api/admin/v1/tenant-subscriptions'
    | '/api/admin/v1/tickets'
    | '/api/public/v1/business_intake'
    | '/api/public/v1/clinics'
    | '/api/public/v1/courses'
    | '/api/public/v1/credentials'
    | '/api/public/v1/eta'
    | '/api/public/v1/fleet'
    | '/api/public/v1/incidents'
    | '/api/public/v1/openapi'
    | '/api/public/v1/screening_orders'
    | '/api/public/v1/stats'
    | '/api/public/v1/web_intake'
    | '/api/public/v1/work_orders'
    | '/api/admin/v1/analytics/kpis'
    | '/api/admin/v1/business-requests/$id'
    | '/api/admin/v1/config/base'
    | '/api/admin/v1/config/overrides'
    | '/api/admin/v1/diagnostics/superadmin'
    | '/api/admin/v1/plans/$id'
    | '/api/admin/v1/subscribers/$id'
    | '/api/admin/v1/tenant-subscriptions/$id'
    | '/api/admin/v1/usage/daily'
    | '/api/public/v1/debug/events'
    | '/api/public/v1/incidents/$id'
    | '/api/public/v1/share/$token'
    | '/api/admin/v1/business-requests/$id/advance'
    | '/api/admin/v1/business-requests/$id/convert'
    | '/api/admin/v1/config/effective/$subscriberId'
    | '/api/admin/v1/payments/$id/validate'
    | '/api/admin/v1/tickets/$id/events'
    | '/api/public/v1/fleet/$id/location'
    | '/api/public/v1/vehicles/$id/credentials'
    | '/api/public/v1/vehicles/$id/defects'
    | '/api/public/v1/vehicles/$id/work_orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/api-docs'
    | '/api-reference'
    | '/auth'
    | '/business-intake'
    | '/clinics'
    | '/contact'
    | '/demo'
    | '/developers'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/website'
    | '/_authenticated/admin'
    | '/_authenticated/audit'
    | '/_authenticated/business'
    | '/_authenticated/call-center'
    | '/_authenticated/compliance'
    | '/_authenticated/developer'
    | '/_authenticated/dispatch'
    | '/_authenticated/fleet'
    | '/_authenticated/patient'
    | '/_authenticated/privileges'
    | '/_authenticated/provider'
    | '/_authenticated/rentals'
    | '/_authenticated/screening'
    | '/_authenticated/superadmin'
    | '/_authenticated/training'
    | '/_authenticated/trips'
    | '/clinics/$city'
    | '/resources/$slug'
    | '/resources/comparison'
    | '/services/$slug'
    | '/trip/$token'
    | '/_authenticated/superadmin/api-docs'
    | '/api/admin/v1/audit'
    | '/api/admin/v1/bugs'
    | '/api/admin/v1/business-requests'
    | '/api/admin/v1/invoices'
    | '/api/admin/v1/openapi'
    | '/api/admin/v1/payments'
    | '/api/admin/v1/plans'
    | '/api/admin/v1/privileges'
    | '/api/admin/v1/promotions'
    | '/api/admin/v1/roles'
    | '/api/admin/v1/subscribers'
    | '/api/admin/v1/subscriptions'
    | '/api/admin/v1/tenant-subscriptions'
    | '/api/admin/v1/tickets'
    | '/api/public/v1/business_intake'
    | '/api/public/v1/clinics'
    | '/api/public/v1/courses'
    | '/api/public/v1/credentials'
    | '/api/public/v1/eta'
    | '/api/public/v1/fleet'
    | '/api/public/v1/incidents'
    | '/api/public/v1/openapi'
    | '/api/public/v1/screening_orders'
    | '/api/public/v1/stats'
    | '/api/public/v1/web_intake'
    | '/api/public/v1/work_orders'
    | '/api/admin/v1/analytics/kpis'
    | '/api/admin/v1/business-requests/$id'
    | '/api/admin/v1/config/base'
    | '/api/admin/v1/config/overrides'
    | '/api/admin/v1/diagnostics/superadmin'
    | '/api/admin/v1/plans/$id'
    | '/api/admin/v1/subscribers/$id'
    | '/api/admin/v1/tenant-subscriptions/$id'
    | '/api/admin/v1/usage/daily'
    | '/api/public/v1/debug/events'
    | '/api/public/v1/incidents/$id'
    | '/api/public/v1/share/$token'
    | '/api/admin/v1/business-requests/$id/advance'
    | '/api/admin/v1/business-requests/$id/convert'
    | '/api/admin/v1/config/effective/$subscriberId'
    | '/api/admin/v1/payments/$id/validate'
    | '/api/admin/v1/tickets/$id/events'
    | '/api/public/v1/fleet/$id/location'
    | '/api/public/v1/vehicles/$id/credentials'
    | '/api/public/v1/vehicles/$id/defects'
    | '/api/public/v1/vehicles/$id/work_orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ApiReferenceRoute: typeof ApiReferenceRoute
  AuthRoute: typeof AuthRoute
  BusinessIntakeRoute: typeof BusinessIntakeRoute
  ClinicsRoute: typeof ClinicsRouteWithChildren
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  DevelopersRoute: typeof DevelopersRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WebsiteRoute: typeof WebsiteRoute
  TripTokenRoute: typeof TripTokenRoute
  ApiAdminV1AuditRoute: typeof ApiAdminV1AuditRoute
  ApiAdminV1BugsRoute: typeof ApiAdminV1BugsRoute
  ApiAdminV1BusinessRequestsRoute: typeof ApiAdminV1BusinessRequestsRouteWithChildren
  ApiAdminV1InvoicesRoute: typeof ApiAdminV1InvoicesRoute
  ApiAdminV1OpenapiRoute: typeof ApiAdminV1OpenapiRoute
  ApiAdminV1PaymentsRoute: typeof ApiAdminV1PaymentsRouteWithChildren
  ApiAdminV1PlansRoute: typeof ApiAdminV1PlansRouteWithChildren
  ApiAdminV1PrivilegesRoute: typeof ApiAdminV1PrivilegesRoute
  ApiAdminV1PromotionsRoute: typeof ApiAdminV1PromotionsRoute
  ApiAdminV1RolesRoute: typeof ApiAdminV1RolesRoute
  ApiAdminV1SubscribersRoute: typeof ApiAdminV1SubscribersRouteWithChildren
  ApiAdminV1SubscriptionsRoute: typeof ApiAdminV1SubscriptionsRoute
  ApiAdminV1TenantSubscriptionsRoute: typeof ApiAdminV1TenantSubscriptionsRouteWithChildren
  ApiAdminV1TicketsRoute: typeof ApiAdminV1TicketsRouteWithChildren
  ApiPublicV1Business_intakeRoute: typeof ApiPublicV1Business_intakeRoute
  ApiPublicV1ClinicsRoute: typeof ApiPublicV1ClinicsRoute
  ApiPublicV1CoursesRoute: typeof ApiPublicV1CoursesRoute
  ApiPublicV1CredentialsRoute: typeof ApiPublicV1CredentialsRoute
  ApiPublicV1EtaRoute: typeof ApiPublicV1EtaRoute
  ApiPublicV1FleetRoute: typeof ApiPublicV1FleetRouteWithChildren
  ApiPublicV1IncidentsRoute: typeof ApiPublicV1IncidentsRouteWithChildren
  ApiPublicV1OpenapiRoute: typeof ApiPublicV1OpenapiRoute
  ApiPublicV1Screening_ordersRoute: typeof ApiPublicV1Screening_ordersRoute
  ApiPublicV1StatsRoute: typeof ApiPublicV1StatsRoute
  ApiPublicV1Web_intakeRoute: typeof ApiPublicV1Web_intakeRoute
  ApiPublicV1Work_ordersRoute: typeof ApiPublicV1Work_ordersRoute
  ApiAdminV1AnalyticsKpisRoute: typeof ApiAdminV1AnalyticsKpisRoute
  ApiAdminV1ConfigBaseRoute: typeof ApiAdminV1ConfigBaseRoute
  ApiAdminV1ConfigOverridesRoute: typeof ApiAdminV1ConfigOverridesRoute
  ApiAdminV1DiagnosticsSuperadminRoute: typeof ApiAdminV1DiagnosticsSuperadminRoute
  ApiAdminV1UsageDailyRoute: typeof ApiAdminV1UsageDailyRoute
  ApiPublicV1DebugEventsRoute: typeof ApiPublicV1DebugEventsRoute
  ApiPublicV1ShareTokenRoute: typeof ApiPublicV1ShareTokenRoute
  ApiAdminV1ConfigEffectiveSubscriberIdRoute: typeof ApiAdminV1ConfigEffectiveSubscriberIdRoute
  ApiPublicV1VehiclesIdCredentialsRoute: typeof ApiPublicV1VehiclesIdCredentialsRoute
  ApiPublicV1VehiclesIdDefectsRoute: typeof ApiPublicV1VehiclesIdDefectsRoute
  ApiPublicV1VehiclesIdWork_ordersRoute: typeof ApiPublicV1VehiclesIdWork_ordersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics': {
      id: '/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof ClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-intake': {
      id: '/business-intake'
      path: '/business-intake'
      fullPath: '/business-intake'
      preLoaderRoute: typeof BusinessIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$token': {
      id: '/trip/$token'
      path: '/trip/$token'
      fullPath: '/trip/$token'
      preLoaderRoute: typeof TripTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/resources/comparison': {
      id: '/resources/comparison'
      path: '/comparison'
      fullPath: '/resources/comparison'
      preLoaderRoute: typeof ResourcesComparisonRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/clinics/$city': {
      id: '/clinics/$city'
      path: '/$city'
      fullPath: '/clinics/$city'
      preLoaderRoute: typeof ClinicsCityRouteImport
      parentRoute: typeof ClinicsRoute
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/screening': {
      id: '/_authenticated/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof AuthenticatedScreeningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rentals': {
      id: '/_authenticated/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof AuthenticatedRentalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider': {
      id: '/_authenticated/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof AuthenticatedProviderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privileges': {
      id: '/_authenticated/privileges'
      path: '/privileges'
      fullPath: '/privileges'
      preLoaderRoute: typeof AuthenticatedPrivilegesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient': {
      id: '/_authenticated/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof AuthenticatedPatientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispatch': {
      id: '/_authenticated/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AuthenticatedDispatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer': {
      id: '/_authenticated/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthenticatedDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/call-center': {
      id: '/_authenticated/call-center'
      path: '/call-center'
      fullPath: '/call-center'
      preLoaderRoute: typeof AuthenticatedCallCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin/api-docs': {
      id: '/_authenticated/superadmin/api-docs'
      path: '/api-docs'
      fullPath: '/superadmin/api-docs'
      preLoaderRoute: typeof AuthenticatedSuperadminApiDocsRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/api/public/v1/work_orders': {
      id: '/api/public/v1/work_orders'
      path: '/api/public/v1/work_orders'
      fullPath: '/api/public/v1/work_orders'
      preLoaderRoute: typeof ApiPublicV1Work_ordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/web_intake': {
      id: '/api/public/v1/web_intake'
      path: '/api/public/v1/web_intake'
      fullPath: '/api/public/v1/web_intake'
      preLoaderRoute: typeof ApiPublicV1Web_intakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/stats': {
      id: '/api/public/v1/stats'
      path: '/api/public/v1/stats'
      fullPath: '/api/public/v1/stats'
      preLoaderRoute: typeof ApiPublicV1StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/screening_orders': {
      id: '/api/public/v1/screening_orders'
      path: '/api/public/v1/screening_orders'
      fullPath: '/api/public/v1/screening_orders'
      preLoaderRoute: typeof ApiPublicV1Screening_ordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/openapi': {
      id: '/api/public/v1/openapi'
      path: '/api/public/v1/openapi'
      fullPath: '/api/public/v1/openapi'
      preLoaderRoute: typeof ApiPublicV1OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/incidents': {
      id: '/api/public/v1/incidents'
      path: '/api/public/v1/incidents'
      fullPath: '/api/public/v1/incidents'
      preLoaderRoute: typeof ApiPublicV1IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/fleet': {
      id: '/api/public/v1/fleet'
      path: '/api/public/v1/fleet'
      fullPath: '/api/public/v1/fleet'
      preLoaderRoute: typeof ApiPublicV1FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/eta': {
      id: '/api/public/v1/eta'
      path: '/api/public/v1/eta'
      fullPath: '/api/public/v1/eta'
      preLoaderRoute: typeof ApiPublicV1EtaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/credentials': {
      id: '/api/public/v1/credentials'
      path: '/api/public/v1/credentials'
      fullPath: '/api/public/v1/credentials'
      preLoaderRoute: typeof ApiPublicV1CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/courses': {
      id: '/api/public/v1/courses'
      path: '/api/public/v1/courses'
      fullPath: '/api/public/v1/courses'
      preLoaderRoute: typeof ApiPublicV1CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/clinics': {
      id: '/api/public/v1/clinics'
      path: '/api/public/v1/clinics'
      fullPath: '/api/public/v1/clinics'
      preLoaderRoute: typeof ApiPublicV1ClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/business_intake': {
      id: '/api/public/v1/business_intake'
      path: '/api/public/v1/business_intake'
      fullPath: '/api/public/v1/business_intake'
      preLoaderRoute: typeof ApiPublicV1Business_intakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/tickets': {
      id: '/api/admin/v1/tickets'
      path: '/api/admin/v1/tickets'
      fullPath: '/api/admin/v1/tickets'
      preLoaderRoute: typeof ApiAdminV1TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/tenant-subscriptions': {
      id: '/api/admin/v1/tenant-subscriptions'
      path: '/api/admin/v1/tenant-subscriptions'
      fullPath: '/api/admin/v1/tenant-subscriptions'
      preLoaderRoute: typeof ApiAdminV1TenantSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/subscriptions': {
      id: '/api/admin/v1/subscriptions'
      path: '/api/admin/v1/subscriptions'
      fullPath: '/api/admin/v1/subscriptions'
      preLoaderRoute: typeof ApiAdminV1SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/subscribers': {
      id: '/api/admin/v1/subscribers'
      path: '/api/admin/v1/subscribers'
      fullPath: '/api/admin/v1/subscribers'
      preLoaderRoute: typeof ApiAdminV1SubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/roles': {
      id: '/api/admin/v1/roles'
      path: '/api/admin/v1/roles'
      fullPath: '/api/admin/v1/roles'
      preLoaderRoute: typeof ApiAdminV1RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/promotions': {
      id: '/api/admin/v1/promotions'
      path: '/api/admin/v1/promotions'
      fullPath: '/api/admin/v1/promotions'
      preLoaderRoute: typeof ApiAdminV1PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/privileges': {
      id: '/api/admin/v1/privileges'
      path: '/api/admin/v1/privileges'
      fullPath: '/api/admin/v1/privileges'
      preLoaderRoute: typeof ApiAdminV1PrivilegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/plans': {
      id: '/api/admin/v1/plans'
      path: '/api/admin/v1/plans'
      fullPath: '/api/admin/v1/plans'
      preLoaderRoute: typeof ApiAdminV1PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/payments': {
      id: '/api/admin/v1/payments'
      path: '/api/admin/v1/payments'
      fullPath: '/api/admin/v1/payments'
      preLoaderRoute: typeof ApiAdminV1PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/openapi': {
      id: '/api/admin/v1/openapi'
      path: '/api/admin/v1/openapi'
      fullPath: '/api/admin/v1/openapi'
      preLoaderRoute: typeof ApiAdminV1OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/invoices': {
      id: '/api/admin/v1/invoices'
      path: '/api/admin/v1/invoices'
      fullPath: '/api/admin/v1/invoices'
      preLoaderRoute: typeof ApiAdminV1InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/business-requests': {
      id: '/api/admin/v1/business-requests'
      path: '/api/admin/v1/business-requests'
      fullPath: '/api/admin/v1/business-requests'
      preLoaderRoute: typeof ApiAdminV1BusinessRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/bugs': {
      id: '/api/admin/v1/bugs'
      path: '/api/admin/v1/bugs'
      fullPath: '/api/admin/v1/bugs'
      preLoaderRoute: typeof ApiAdminV1BugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/audit': {
      id: '/api/admin/v1/audit'
      path: '/api/admin/v1/audit'
      fullPath: '/api/admin/v1/audit'
      preLoaderRoute: typeof ApiAdminV1AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/share/$token': {
      id: '/api/public/v1/share/$token'
      path: '/api/public/v1/share/$token'
      fullPath: '/api/public/v1/share/$token'
      preLoaderRoute: typeof ApiPublicV1ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/incidents/$id': {
      id: '/api/public/v1/incidents/$id'
      path: '/$id'
      fullPath: '/api/public/v1/incidents/$id'
      preLoaderRoute: typeof ApiPublicV1IncidentsIdRouteImport
      parentRoute: typeof ApiPublicV1IncidentsRoute
    }
    '/api/public/v1/debug/events': {
      id: '/api/public/v1/debug/events'
      path: '/api/public/v1/debug/events'
      fullPath: '/api/public/v1/debug/events'
      preLoaderRoute: typeof ApiPublicV1DebugEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/usage/daily': {
      id: '/api/admin/v1/usage/daily'
      path: '/api/admin/v1/usage/daily'
      fullPath: '/api/admin/v1/usage/daily'
      preLoaderRoute: typeof ApiAdminV1UsageDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/tenant-subscriptions/$id': {
      id: '/api/admin/v1/tenant-subscriptions/$id'
      path: '/$id'
      fullPath: '/api/admin/v1/tenant-subscriptions/$id'
      preLoaderRoute: typeof ApiAdminV1TenantSubscriptionsIdRouteImport
      parentRoute: typeof ApiAdminV1TenantSubscriptionsRoute
    }
    '/api/admin/v1/subscribers/$id': {
      id: '/api/admin/v1/subscribers/$id'
      path: '/$id'
      fullPath: '/api/admin/v1/subscribers/$id'
      preLoaderRoute: typeof ApiAdminV1SubscribersIdRouteImport
      parentRoute: typeof ApiAdminV1SubscribersRoute
    }
    '/api/admin/v1/plans/$id': {
      id: '/api/admin/v1/plans/$id'
      path: '/$id'
      fullPath: '/api/admin/v1/plans/$id'
      preLoaderRoute: typeof ApiAdminV1PlansIdRouteImport
      parentRoute: typeof ApiAdminV1PlansRoute
    }
    '/api/admin/v1/diagnostics/superadmin': {
      id: '/api/admin/v1/diagnostics/superadmin'
      path: '/api/admin/v1/diagnostics/superadmin'
      fullPath: '/api/admin/v1/diagnostics/superadmin'
      preLoaderRoute: typeof ApiAdminV1DiagnosticsSuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/config/overrides': {
      id: '/api/admin/v1/config/overrides'
      path: '/api/admin/v1/config/overrides'
      fullPath: '/api/admin/v1/config/overrides'
      preLoaderRoute: typeof ApiAdminV1ConfigOverridesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/config/base': {
      id: '/api/admin/v1/config/base'
      path: '/api/admin/v1/config/base'
      fullPath: '/api/admin/v1/config/base'
      preLoaderRoute: typeof ApiAdminV1ConfigBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/business-requests/$id': {
      id: '/api/admin/v1/business-requests/$id'
      path: '/$id'
      fullPath: '/api/admin/v1/business-requests/$id'
      preLoaderRoute: typeof ApiAdminV1BusinessRequestsIdRouteImport
      parentRoute: typeof ApiAdminV1BusinessRequestsRoute
    }
    '/api/admin/v1/analytics/kpis': {
      id: '/api/admin/v1/analytics/kpis'
      path: '/api/admin/v1/analytics/kpis'
      fullPath: '/api/admin/v1/analytics/kpis'
      preLoaderRoute: typeof ApiAdminV1AnalyticsKpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/vehicles/$id/work_orders': {
      id: '/api/public/v1/vehicles/$id/work_orders'
      path: '/api/public/v1/vehicles/$id/work_orders'
      fullPath: '/api/public/v1/vehicles/$id/work_orders'
      preLoaderRoute: typeof ApiPublicV1VehiclesIdWork_ordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/vehicles/$id/defects': {
      id: '/api/public/v1/vehicles/$id/defects'
      path: '/api/public/v1/vehicles/$id/defects'
      fullPath: '/api/public/v1/vehicles/$id/defects'
      preLoaderRoute: typeof ApiPublicV1VehiclesIdDefectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/vehicles/$id/credentials': {
      id: '/api/public/v1/vehicles/$id/credentials'
      path: '/api/public/v1/vehicles/$id/credentials'
      fullPath: '/api/public/v1/vehicles/$id/credentials'
      preLoaderRoute: typeof ApiPublicV1VehiclesIdCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/fleet/$id/location': {
      id: '/api/public/v1/fleet/$id/location'
      path: '/$id/location'
      fullPath: '/api/public/v1/fleet/$id/location'
      preLoaderRoute: typeof ApiPublicV1FleetIdLocationRouteImport
      parentRoute: typeof ApiPublicV1FleetRoute
    }
    '/api/admin/v1/tickets/$id/events': {
      id: '/api/admin/v1/tickets/$id/events'
      path: '/$id/events'
      fullPath: '/api/admin/v1/tickets/$id/events'
      preLoaderRoute: typeof ApiAdminV1TicketsIdEventsRouteImport
      parentRoute: typeof ApiAdminV1TicketsRoute
    }
    '/api/admin/v1/payments/$id/validate': {
      id: '/api/admin/v1/payments/$id/validate'
      path: '/$id/validate'
      fullPath: '/api/admin/v1/payments/$id/validate'
      preLoaderRoute: typeof ApiAdminV1PaymentsIdValidateRouteImport
      parentRoute: typeof ApiAdminV1PaymentsRoute
    }
    '/api/admin/v1/config/effective/$subscriberId': {
      id: '/api/admin/v1/config/effective/$subscriberId'
      path: '/api/admin/v1/config/effective/$subscriberId'
      fullPath: '/api/admin/v1/config/effective/$subscriberId'
      preLoaderRoute: typeof ApiAdminV1ConfigEffectiveSubscriberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/v1/business-requests/$id/convert': {
      id: '/api/admin/v1/business-requests/$id/convert'
      path: '/convert'
      fullPath: '/api/admin/v1/business-requests/$id/convert'
      preLoaderRoute: typeof ApiAdminV1BusinessRequestsIdConvertRouteImport
      parentRoute: typeof ApiAdminV1BusinessRequestsIdRoute
    }
    '/api/admin/v1/business-requests/$id/advance': {
      id: '/api/admin/v1/business-requests/$id/advance'
      path: '/advance'
      fullPath: '/api/admin/v1/business-requests/$id/advance'
      preLoaderRoute: typeof ApiAdminV1BusinessRequestsIdAdvanceRouteImport
      parentRoute: typeof ApiAdminV1BusinessRequestsIdRoute
    }
  }
}

interface AuthenticatedSuperadminRouteChildren {
  AuthenticatedSuperadminApiDocsRoute: typeof AuthenticatedSuperadminApiDocsRoute
}

const AuthenticatedSuperadminRouteChildren: AuthenticatedSuperadminRouteChildren =
  {
    AuthenticatedSuperadminApiDocsRoute: AuthenticatedSuperadminApiDocsRoute,
  }

const AuthenticatedSuperadminRouteWithChildren =
  AuthenticatedSuperadminRoute._addFileChildren(
    AuthenticatedSuperadminRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBusinessRoute: typeof AuthenticatedBusinessRoute
  AuthenticatedCallCenterRoute: typeof AuthenticatedCallCenterRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedDeveloperRoute: typeof AuthenticatedDeveloperRoute
  AuthenticatedDispatchRoute: typeof AuthenticatedDispatchRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRoute
  AuthenticatedPatientRoute: typeof AuthenticatedPatientRoute
  AuthenticatedPrivilegesRoute: typeof AuthenticatedPrivilegesRoute
  AuthenticatedProviderRoute: typeof AuthenticatedProviderRoute
  AuthenticatedRentalsRoute: typeof AuthenticatedRentalsRoute
  AuthenticatedScreeningRoute: typeof AuthenticatedScreeningRoute
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRouteWithChildren
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBusinessRoute: AuthenticatedBusinessRoute,
  AuthenticatedCallCenterRoute: AuthenticatedCallCenterRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedDeveloperRoute: AuthenticatedDeveloperRoute,
  AuthenticatedDispatchRoute: AuthenticatedDispatchRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRoute,
  AuthenticatedPatientRoute: AuthenticatedPatientRoute,
  AuthenticatedPrivilegesRoute: AuthenticatedPrivilegesRoute,
  AuthenticatedProviderRoute: AuthenticatedProviderRoute,
  AuthenticatedRentalsRoute: AuthenticatedRentalsRoute,
  AuthenticatedScreeningRoute: AuthenticatedScreeningRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRouteWithChildren,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClinicsRouteChildren {
  ClinicsCityRoute: typeof ClinicsCityRoute
}

const ClinicsRouteChildren: ClinicsRouteChildren = {
  ClinicsCityRoute: ClinicsCityRoute,
}

const ClinicsRouteWithChildren =
  ClinicsRoute._addFileChildren(ClinicsRouteChildren)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesComparisonRoute: typeof ResourcesComparisonRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesComparisonRoute: ResourcesComparisonRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface ApiAdminV1BusinessRequestsIdRouteChildren {
  ApiAdminV1BusinessRequestsIdAdvanceRoute: typeof ApiAdminV1BusinessRequestsIdAdvanceRoute
  ApiAdminV1BusinessRequestsIdConvertRoute: typeof ApiAdminV1BusinessRequestsIdConvertRoute
}

const ApiAdminV1BusinessRequestsIdRouteChildren: ApiAdminV1BusinessRequestsIdRouteChildren =
  {
    ApiAdminV1BusinessRequestsIdAdvanceRoute:
      ApiAdminV1BusinessRequestsIdAdvanceRoute,
    ApiAdminV1BusinessRequestsIdConvertRoute:
      ApiAdminV1BusinessRequestsIdConvertRoute,
  }

const ApiAdminV1BusinessRequestsIdRouteWithChildren =
  ApiAdminV1BusinessRequestsIdRoute._addFileChildren(
    ApiAdminV1BusinessRequestsIdRouteChildren,
  )

interface ApiAdminV1BusinessRequestsRouteChildren {
  ApiAdminV1BusinessRequestsIdRoute: typeof ApiAdminV1BusinessRequestsIdRouteWithChildren
}

const ApiAdminV1BusinessRequestsRouteChildren: ApiAdminV1BusinessRequestsRouteChildren =
  {
    ApiAdminV1BusinessRequestsIdRoute:
      ApiAdminV1BusinessRequestsIdRouteWithChildren,
  }

const ApiAdminV1BusinessRequestsRouteWithChildren =
  ApiAdminV1BusinessRequestsRoute._addFileChildren(
    ApiAdminV1BusinessRequestsRouteChildren,
  )

interface ApiAdminV1PaymentsRouteChildren {
  ApiAdminV1PaymentsIdValidateRoute: typeof ApiAdminV1PaymentsIdValidateRoute
}

const ApiAdminV1PaymentsRouteChildren: ApiAdminV1PaymentsRouteChildren = {
  ApiAdminV1PaymentsIdValidateRoute: ApiAdminV1PaymentsIdValidateRoute,
}

const ApiAdminV1PaymentsRouteWithChildren =
  ApiAdminV1PaymentsRoute._addFileChildren(ApiAdminV1PaymentsRouteChildren)

interface ApiAdminV1PlansRouteChildren {
  ApiAdminV1PlansIdRoute: typeof ApiAdminV1PlansIdRoute
}

const ApiAdminV1PlansRouteChildren: ApiAdminV1PlansRouteChildren = {
  ApiAdminV1PlansIdRoute: ApiAdminV1PlansIdRoute,
}

const ApiAdminV1PlansRouteWithChildren = ApiAdminV1PlansRoute._addFileChildren(
  ApiAdminV1PlansRouteChildren,
)

interface ApiAdminV1SubscribersRouteChildren {
  ApiAdminV1SubscribersIdRoute: typeof ApiAdminV1SubscribersIdRoute
}

const ApiAdminV1SubscribersRouteChildren: ApiAdminV1SubscribersRouteChildren = {
  ApiAdminV1SubscribersIdRoute: ApiAdminV1SubscribersIdRoute,
}

const ApiAdminV1SubscribersRouteWithChildren =
  ApiAdminV1SubscribersRoute._addFileChildren(
    ApiAdminV1SubscribersRouteChildren,
  )

interface ApiAdminV1TenantSubscriptionsRouteChildren {
  ApiAdminV1TenantSubscriptionsIdRoute: typeof ApiAdminV1TenantSubscriptionsIdRoute
}

const ApiAdminV1TenantSubscriptionsRouteChildren: ApiAdminV1TenantSubscriptionsRouteChildren =
  {
    ApiAdminV1TenantSubscriptionsIdRoute: ApiAdminV1TenantSubscriptionsIdRoute,
  }

const ApiAdminV1TenantSubscriptionsRouteWithChildren =
  ApiAdminV1TenantSubscriptionsRoute._addFileChildren(
    ApiAdminV1TenantSubscriptionsRouteChildren,
  )

interface ApiAdminV1TicketsRouteChildren {
  ApiAdminV1TicketsIdEventsRoute: typeof ApiAdminV1TicketsIdEventsRoute
}

const ApiAdminV1TicketsRouteChildren: ApiAdminV1TicketsRouteChildren = {
  ApiAdminV1TicketsIdEventsRoute: ApiAdminV1TicketsIdEventsRoute,
}

const ApiAdminV1TicketsRouteWithChildren =
  ApiAdminV1TicketsRoute._addFileChildren(ApiAdminV1TicketsRouteChildren)

interface ApiPublicV1FleetRouteChildren {
  ApiPublicV1FleetIdLocationRoute: typeof ApiPublicV1FleetIdLocationRoute
}

const ApiPublicV1FleetRouteChildren: ApiPublicV1FleetRouteChildren = {
  ApiPublicV1FleetIdLocationRoute: ApiPublicV1FleetIdLocationRoute,
}

const ApiPublicV1FleetRouteWithChildren =
  ApiPublicV1FleetRoute._addFileChildren(ApiPublicV1FleetRouteChildren)

interface ApiPublicV1IncidentsRouteChildren {
  ApiPublicV1IncidentsIdRoute: typeof ApiPublicV1IncidentsIdRoute
}

const ApiPublicV1IncidentsRouteChildren: ApiPublicV1IncidentsRouteChildren = {
  ApiPublicV1IncidentsIdRoute: ApiPublicV1IncidentsIdRoute,
}

const ApiPublicV1IncidentsRouteWithChildren =
  ApiPublicV1IncidentsRoute._addFileChildren(ApiPublicV1IncidentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApiDocsRoute: ApiDocsRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  AuthRoute: AuthRoute,
  BusinessIntakeRoute: BusinessIntakeRoute,
  ClinicsRoute: ClinicsRouteWithChildren,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  DevelopersRoute: DevelopersRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WebsiteRoute: WebsiteRoute,
  TripTokenRoute: TripTokenRoute,
  ApiAdminV1AuditRoute: ApiAdminV1AuditRoute,
  ApiAdminV1BugsRoute: ApiAdminV1BugsRoute,
  ApiAdminV1BusinessRequestsRoute: ApiAdminV1BusinessRequestsRouteWithChildren,
  ApiAdminV1InvoicesRoute: ApiAdminV1InvoicesRoute,
  ApiAdminV1OpenapiRoute: ApiAdminV1OpenapiRoute,
  ApiAdminV1PaymentsRoute: ApiAdminV1PaymentsRouteWithChildren,
  ApiAdminV1PlansRoute: ApiAdminV1PlansRouteWithChildren,
  ApiAdminV1PrivilegesRoute: ApiAdminV1PrivilegesRoute,
  ApiAdminV1PromotionsRoute: ApiAdminV1PromotionsRoute,
  ApiAdminV1RolesRoute: ApiAdminV1RolesRoute,
  ApiAdminV1SubscribersRoute: ApiAdminV1SubscribersRouteWithChildren,
  ApiAdminV1SubscriptionsRoute: ApiAdminV1SubscriptionsRoute,
  ApiAdminV1TenantSubscriptionsRoute:
    ApiAdminV1TenantSubscriptionsRouteWithChildren,
  ApiAdminV1TicketsRoute: ApiAdminV1TicketsRouteWithChildren,
  ApiPublicV1Business_intakeRoute: ApiPublicV1Business_intakeRoute,
  ApiPublicV1ClinicsRoute: ApiPublicV1ClinicsRoute,
  ApiPublicV1CoursesRoute: ApiPublicV1CoursesRoute,
  ApiPublicV1CredentialsRoute: ApiPublicV1CredentialsRoute,
  ApiPublicV1EtaRoute: ApiPublicV1EtaRoute,
  ApiPublicV1FleetRoute: ApiPublicV1FleetRouteWithChildren,
  ApiPublicV1IncidentsRoute: ApiPublicV1IncidentsRouteWithChildren,
  ApiPublicV1OpenapiRoute: ApiPublicV1OpenapiRoute,
  ApiPublicV1Screening_ordersRoute: ApiPublicV1Screening_ordersRoute,
  ApiPublicV1StatsRoute: ApiPublicV1StatsRoute,
  ApiPublicV1Web_intakeRoute: ApiPublicV1Web_intakeRoute,
  ApiPublicV1Work_ordersRoute: ApiPublicV1Work_ordersRoute,
  ApiAdminV1AnalyticsKpisRoute: ApiAdminV1AnalyticsKpisRoute,
  ApiAdminV1ConfigBaseRoute: ApiAdminV1ConfigBaseRoute,
  ApiAdminV1ConfigOverridesRoute: ApiAdminV1ConfigOverridesRoute,
  ApiAdminV1DiagnosticsSuperadminRoute: ApiAdminV1DiagnosticsSuperadminRoute,
  ApiAdminV1UsageDailyRoute: ApiAdminV1UsageDailyRoute,
  ApiPublicV1DebugEventsRoute: ApiPublicV1DebugEventsRoute,
  ApiPublicV1ShareTokenRoute: ApiPublicV1ShareTokenRoute,
  ApiAdminV1ConfigEffectiveSubscriberIdRoute:
    ApiAdminV1ConfigEffectiveSubscriberIdRoute,
  ApiPublicV1VehiclesIdCredentialsRoute: ApiPublicV1VehiclesIdCredentialsRoute,
  ApiPublicV1VehiclesIdDefectsRoute: ApiPublicV1VehiclesIdDefectsRoute,
  ApiPublicV1VehiclesIdWork_ordersRoute: ApiPublicV1VehiclesIdWork_ordersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
