/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClinicsRouteImport } from './routes/clinics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripTokenRouteImport } from './routes/trip.$token'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AuthenticatedTripsRouteImport } from './routes/_authenticated/trips'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated/training'
import { Route as AuthenticatedScreeningRouteImport } from './routes/_authenticated/screening'
import { Route as AuthenticatedRentalsRouteImport } from './routes/_authenticated/rentals'
import { Route as AuthenticatedProviderRouteImport } from './routes/_authenticated/provider'
import { Route as AuthenticatedPatientRouteImport } from './routes/_authenticated/patient'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated/fleet'
import { Route as AuthenticatedDispatchRouteImport } from './routes/_authenticated/dispatch'
import { Route as AuthenticatedDeveloperRouteImport } from './routes/_authenticated/developer'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedCallCenterRouteImport } from './routes/_authenticated/call-center'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicV1Work_ordersRouteImport } from './routes/api/public/v1/work_orders'
import { Route as ApiPublicV1Web_intakeRouteImport } from './routes/api/public/v1/web_intake'
import { Route as ApiPublicV1Screening_ordersRouteImport } from './routes/api/public/v1/screening_orders'
import { Route as ApiPublicV1OpenapiRouteImport } from './routes/api/public/v1/openapi'
import { Route as ApiPublicV1IncidentsRouteImport } from './routes/api/public/v1/incidents'
import { Route as ApiPublicV1FleetRouteImport } from './routes/api/public/v1/fleet'
import { Route as ApiPublicV1EtaRouteImport } from './routes/api/public/v1/eta'
import { Route as ApiPublicV1CredentialsRouteImport } from './routes/api/public/v1/credentials'
import { Route as ApiPublicV1CoursesRouteImport } from './routes/api/public/v1/courses'
import { Route as ApiPublicV1ClinicsRouteImport } from './routes/api/public/v1/clinics'
import { Route as ApiPublicV1ShareTokenRouteImport } from './routes/api/public/v1/share.$token'
import { Route as ApiPublicV1IncidentsIdRouteImport } from './routes/api/public/v1/incidents.$id'
import { Route as ApiPublicV1VehiclesIdWork_ordersRouteImport } from './routes/api/public/v1/vehicles.$id.work_orders'
import { Route as ApiPublicV1VehiclesIdDefectsRouteImport } from './routes/api/public/v1/vehicles.$id.defects'
import { Route as ApiPublicV1VehiclesIdCredentialsRouteImport } from './routes/api/public/v1/vehicles.$id.credentials'
import { Route as ApiPublicV1FleetIdLocationRouteImport } from './routes/api/public/v1/fleet.$id.location'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsRoute = ClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTokenRoute = TripTokenRouteImport.update({
  id: '/trip/$token',
  path: '/trip/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const AuthenticatedTripsRoute = AuthenticatedTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScreeningRoute = AuthenticatedScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRentalsRoute = AuthenticatedRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProviderRoute = AuthenticatedProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientRoute = AuthenticatedPatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispatchRoute = AuthenticatedDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeveloperRoute = AuthenticatedDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallCenterRoute = AuthenticatedCallCenterRouteImport.update({
  id: '/call-center',
  path: '/call-center',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicV1Work_ordersRoute = ApiPublicV1Work_ordersRouteImport.update({
  id: '/api/public/v1/work_orders',
  path: '/api/public/v1/work_orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1Web_intakeRoute = ApiPublicV1Web_intakeRouteImport.update({
  id: '/api/public/v1/web_intake',
  path: '/api/public/v1/web_intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1Screening_ordersRoute =
  ApiPublicV1Screening_ordersRouteImport.update({
    id: '/api/public/v1/screening_orders',
    path: '/api/public/v1/screening_orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1OpenapiRoute = ApiPublicV1OpenapiRouteImport.update({
  id: '/api/public/v1/openapi',
  path: '/api/public/v1/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1IncidentsRoute = ApiPublicV1IncidentsRouteImport.update({
  id: '/api/public/v1/incidents',
  path: '/api/public/v1/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1FleetRoute = ApiPublicV1FleetRouteImport.update({
  id: '/api/public/v1/fleet',
  path: '/api/public/v1/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1EtaRoute = ApiPublicV1EtaRouteImport.update({
  id: '/api/public/v1/eta',
  path: '/api/public/v1/eta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CredentialsRoute = ApiPublicV1CredentialsRouteImport.update({
  id: '/api/public/v1/credentials',
  path: '/api/public/v1/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CoursesRoute = ApiPublicV1CoursesRouteImport.update({
  id: '/api/public/v1/courses',
  path: '/api/public/v1/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ClinicsRoute = ApiPublicV1ClinicsRouteImport.update({
  id: '/api/public/v1/clinics',
  path: '/api/public/v1/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ShareTokenRoute = ApiPublicV1ShareTokenRouteImport.update({
  id: '/api/public/v1/share/$token',
  path: '/api/public/v1/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1IncidentsIdRoute = ApiPublicV1IncidentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1IncidentsRoute,
} as any)
const ApiPublicV1VehiclesIdWork_ordersRoute =
  ApiPublicV1VehiclesIdWork_ordersRouteImport.update({
    id: '/api/public/v1/vehicles/$id/work_orders',
    path: '/api/public/v1/vehicles/$id/work_orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1VehiclesIdDefectsRoute =
  ApiPublicV1VehiclesIdDefectsRouteImport.update({
    id: '/api/public/v1/vehicles/$id/defects',
    path: '/api/public/v1/vehicles/$id/defects',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1VehiclesIdCredentialsRoute =
  ApiPublicV1VehiclesIdCredentialsRouteImport.update({
    id: '/api/public/v1/vehicles/$id/credentials',
    path: '/api/public/v1/vehicles/$id/credentials',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1FleetIdLocationRoute =
  ApiPublicV1FleetIdLocationRouteImport.update({
    id: '/$id/location',
    path: '/$id/location',
    getParentRoute: () => ApiPublicV1FleetRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/clinics': typeof ClinicsRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/call-center': typeof AuthenticatedCallCenterRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/dispatch': typeof AuthenticatedDispatchRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/patient': typeof AuthenticatedPatientRoute
  '/provider': typeof AuthenticatedProviderRoute
  '/rentals': typeof AuthenticatedRentalsRoute
  '/screening': typeof AuthenticatedScreeningRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/trip/$token': typeof TripTokenRoute
  '/api/public/v1/clinics': typeof ApiPublicV1ClinicsRoute
  '/api/public/v1/courses': typeof ApiPublicV1CoursesRoute
  '/api/public/v1/credentials': typeof ApiPublicV1CredentialsRoute
  '/api/public/v1/eta': typeof ApiPublicV1EtaRoute
  '/api/public/v1/fleet': typeof ApiPublicV1FleetRouteWithChildren
  '/api/public/v1/incidents': typeof ApiPublicV1IncidentsRouteWithChildren
  '/api/public/v1/openapi': typeof ApiPublicV1OpenapiRoute
  '/api/public/v1/screening_orders': typeof ApiPublicV1Screening_ordersRoute
  '/api/public/v1/web_intake': typeof ApiPublicV1Web_intakeRoute
  '/api/public/v1/work_orders': typeof ApiPublicV1Work_ordersRoute
  '/api/public/v1/incidents/$id': typeof ApiPublicV1IncidentsIdRoute
  '/api/public/v1/share/$token': typeof ApiPublicV1ShareTokenRoute
  '/api/public/v1/fleet/$id/location': typeof ApiPublicV1FleetIdLocationRoute
  '/api/public/v1/vehicles/$id/credentials': typeof ApiPublicV1VehiclesIdCredentialsRoute
  '/api/public/v1/vehicles/$id/defects': typeof ApiPublicV1VehiclesIdDefectsRoute
  '/api/public/v1/vehicles/$id/work_orders': typeof ApiPublicV1VehiclesIdWork_ordersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/clinics': typeof ClinicsRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/call-center': typeof AuthenticatedCallCenterRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/developer': typeof AuthenticatedDeveloperRoute
  '/dispatch': typeof AuthenticatedDispatchRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/patient': typeof AuthenticatedPatientRoute
  '/provider': typeof AuthenticatedProviderRoute
  '/rentals': typeof AuthenticatedRentalsRoute
  '/screening': typeof AuthenticatedScreeningRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/trips': typeof AuthenticatedTripsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/trip/$token': typeof TripTokenRoute
  '/api/public/v1/clinics': typeof ApiPublicV1ClinicsRoute
  '/api/public/v1/courses': typeof ApiPublicV1CoursesRoute
  '/api/public/v1/credentials': typeof ApiPublicV1CredentialsRoute
  '/api/public/v1/eta': typeof ApiPublicV1EtaRoute
  '/api/public/v1/fleet': typeof ApiPublicV1FleetRouteWithChildren
  '/api/public/v1/incidents': typeof ApiPublicV1IncidentsRouteWithChildren
  '/api/public/v1/openapi': typeof ApiPublicV1OpenapiRoute
  '/api/public/v1/screening_orders': typeof ApiPublicV1Screening_ordersRoute
  '/api/public/v1/web_intake': typeof ApiPublicV1Web_intakeRoute
  '/api/public/v1/work_orders': typeof ApiPublicV1Work_ordersRoute
  '/api/public/v1/incidents/$id': typeof ApiPublicV1IncidentsIdRoute
  '/api/public/v1/share/$token': typeof ApiPublicV1ShareTokenRoute
  '/api/public/v1/fleet/$id/location': typeof ApiPublicV1FleetIdLocationRoute
  '/api/public/v1/vehicles/$id/credentials': typeof ApiPublicV1VehiclesIdCredentialsRoute
  '/api/public/v1/vehicles/$id/defects': typeof ApiPublicV1VehiclesIdDefectsRoute
  '/api/public/v1/vehicles/$id/work_orders': typeof ApiPublicV1VehiclesIdWork_ordersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/clinics': typeof ClinicsRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/call-center': typeof AuthenticatedCallCenterRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/developer': typeof AuthenticatedDeveloperRoute
  '/_authenticated/dispatch': typeof AuthenticatedDispatchRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRoute
  '/_authenticated/patient': typeof AuthenticatedPatientRoute
  '/_authenticated/provider': typeof AuthenticatedProviderRoute
  '/_authenticated/rentals': typeof AuthenticatedRentalsRoute
  '/_authenticated/screening': typeof AuthenticatedScreeningRoute
  '/_authenticated/training': typeof AuthenticatedTrainingRoute
  '/_authenticated/trips': typeof AuthenticatedTripsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/trip/$token': typeof TripTokenRoute
  '/api/public/v1/clinics': typeof ApiPublicV1ClinicsRoute
  '/api/public/v1/courses': typeof ApiPublicV1CoursesRoute
  '/api/public/v1/credentials': typeof ApiPublicV1CredentialsRoute
  '/api/public/v1/eta': typeof ApiPublicV1EtaRoute
  '/api/public/v1/fleet': typeof ApiPublicV1FleetRouteWithChildren
  '/api/public/v1/incidents': typeof ApiPublicV1IncidentsRouteWithChildren
  '/api/public/v1/openapi': typeof ApiPublicV1OpenapiRoute
  '/api/public/v1/screening_orders': typeof ApiPublicV1Screening_ordersRoute
  '/api/public/v1/web_intake': typeof ApiPublicV1Web_intakeRoute
  '/api/public/v1/work_orders': typeof ApiPublicV1Work_ordersRoute
  '/api/public/v1/incidents/$id': typeof ApiPublicV1IncidentsIdRoute
  '/api/public/v1/share/$token': typeof ApiPublicV1ShareTokenRoute
  '/api/public/v1/fleet/$id/location': typeof ApiPublicV1FleetIdLocationRoute
  '/api/public/v1/vehicles/$id/credentials': typeof ApiPublicV1VehiclesIdCredentialsRoute
  '/api/public/v1/vehicles/$id/defects': typeof ApiPublicV1VehiclesIdDefectsRoute
  '/api/public/v1/vehicles/$id/work_orders': typeof ApiPublicV1VehiclesIdWork_ordersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-docs'
    | '/auth'
    | '/clinics'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/admin'
    | '/audit'
    | '/call-center'
    | '/compliance'
    | '/developer'
    | '/dispatch'
    | '/fleet'
    | '/patient'
    | '/provider'
    | '/rentals'
    | '/screening'
    | '/training'
    | '/trips'
    | '/services/$slug'
    | '/trip/$token'
    | '/api/public/v1/clinics'
    | '/api/public/v1/courses'
    | '/api/public/v1/credentials'
    | '/api/public/v1/eta'
    | '/api/public/v1/fleet'
    | '/api/public/v1/incidents'
    | '/api/public/v1/openapi'
    | '/api/public/v1/screening_orders'
    | '/api/public/v1/web_intake'
    | '/api/public/v1/work_orders'
    | '/api/public/v1/incidents/$id'
    | '/api/public/v1/share/$token'
    | '/api/public/v1/fleet/$id/location'
    | '/api/public/v1/vehicles/$id/credentials'
    | '/api/public/v1/vehicles/$id/defects'
    | '/api/public/v1/vehicles/$id/work_orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-docs'
    | '/auth'
    | '/clinics'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/admin'
    | '/audit'
    | '/call-center'
    | '/compliance'
    | '/developer'
    | '/dispatch'
    | '/fleet'
    | '/patient'
    | '/provider'
    | '/rentals'
    | '/screening'
    | '/training'
    | '/trips'
    | '/services/$slug'
    | '/trip/$token'
    | '/api/public/v1/clinics'
    | '/api/public/v1/courses'
    | '/api/public/v1/credentials'
    | '/api/public/v1/eta'
    | '/api/public/v1/fleet'
    | '/api/public/v1/incidents'
    | '/api/public/v1/openapi'
    | '/api/public/v1/screening_orders'
    | '/api/public/v1/web_intake'
    | '/api/public/v1/work_orders'
    | '/api/public/v1/incidents/$id'
    | '/api/public/v1/share/$token'
    | '/api/public/v1/fleet/$id/location'
    | '/api/public/v1/vehicles/$id/credentials'
    | '/api/public/v1/vehicles/$id/defects'
    | '/api/public/v1/vehicles/$id/work_orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/api-docs'
    | '/auth'
    | '/clinics'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/audit'
    | '/_authenticated/call-center'
    | '/_authenticated/compliance'
    | '/_authenticated/developer'
    | '/_authenticated/dispatch'
    | '/_authenticated/fleet'
    | '/_authenticated/patient'
    | '/_authenticated/provider'
    | '/_authenticated/rentals'
    | '/_authenticated/screening'
    | '/_authenticated/training'
    | '/_authenticated/trips'
    | '/services/$slug'
    | '/trip/$token'
    | '/api/public/v1/clinics'
    | '/api/public/v1/courses'
    | '/api/public/v1/credentials'
    | '/api/public/v1/eta'
    | '/api/public/v1/fleet'
    | '/api/public/v1/incidents'
    | '/api/public/v1/openapi'
    | '/api/public/v1/screening_orders'
    | '/api/public/v1/web_intake'
    | '/api/public/v1/work_orders'
    | '/api/public/v1/incidents/$id'
    | '/api/public/v1/share/$token'
    | '/api/public/v1/fleet/$id/location'
    | '/api/public/v1/vehicles/$id/credentials'
    | '/api/public/v1/vehicles/$id/defects'
    | '/api/public/v1/vehicles/$id/work_orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApiDocsRoute: typeof ApiDocsRoute
  AuthRoute: typeof AuthRoute
  ClinicsRoute: typeof ClinicsRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TripTokenRoute: typeof TripTokenRoute
  ApiPublicV1ClinicsRoute: typeof ApiPublicV1ClinicsRoute
  ApiPublicV1CoursesRoute: typeof ApiPublicV1CoursesRoute
  ApiPublicV1CredentialsRoute: typeof ApiPublicV1CredentialsRoute
  ApiPublicV1EtaRoute: typeof ApiPublicV1EtaRoute
  ApiPublicV1FleetRoute: typeof ApiPublicV1FleetRouteWithChildren
  ApiPublicV1IncidentsRoute: typeof ApiPublicV1IncidentsRouteWithChildren
  ApiPublicV1OpenapiRoute: typeof ApiPublicV1OpenapiRoute
  ApiPublicV1Screening_ordersRoute: typeof ApiPublicV1Screening_ordersRoute
  ApiPublicV1Web_intakeRoute: typeof ApiPublicV1Web_intakeRoute
  ApiPublicV1Work_ordersRoute: typeof ApiPublicV1Work_ordersRoute
  ApiPublicV1ShareTokenRoute: typeof ApiPublicV1ShareTokenRoute
  ApiPublicV1VehiclesIdCredentialsRoute: typeof ApiPublicV1VehiclesIdCredentialsRoute
  ApiPublicV1VehiclesIdDefectsRoute: typeof ApiPublicV1VehiclesIdDefectsRoute
  ApiPublicV1VehiclesIdWork_ordersRoute: typeof ApiPublicV1VehiclesIdWork_ordersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics': {
      id: '/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof ClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$token': {
      id: '/trip/$token'
      path: '/trip/$token'
      fullPath: '/trip/$token'
      preLoaderRoute: typeof TripTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/_authenticated/trips': {
      id: '/_authenticated/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AuthenticatedTripsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/screening': {
      id: '/_authenticated/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof AuthenticatedScreeningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rentals': {
      id: '/_authenticated/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof AuthenticatedRentalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider': {
      id: '/_authenticated/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof AuthenticatedProviderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient': {
      id: '/_authenticated/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof AuthenticatedPatientRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispatch': {
      id: '/_authenticated/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AuthenticatedDispatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/developer': {
      id: '/_authenticated/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthenticatedDeveloperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/call-center': {
      id: '/_authenticated/call-center'
      path: '/call-center'
      fullPath: '/call-center'
      preLoaderRoute: typeof AuthenticatedCallCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/v1/work_orders': {
      id: '/api/public/v1/work_orders'
      path: '/api/public/v1/work_orders'
      fullPath: '/api/public/v1/work_orders'
      preLoaderRoute: typeof ApiPublicV1Work_ordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/web_intake': {
      id: '/api/public/v1/web_intake'
      path: '/api/public/v1/web_intake'
      fullPath: '/api/public/v1/web_intake'
      preLoaderRoute: typeof ApiPublicV1Web_intakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/screening_orders': {
      id: '/api/public/v1/screening_orders'
      path: '/api/public/v1/screening_orders'
      fullPath: '/api/public/v1/screening_orders'
      preLoaderRoute: typeof ApiPublicV1Screening_ordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/openapi': {
      id: '/api/public/v1/openapi'
      path: '/api/public/v1/openapi'
      fullPath: '/api/public/v1/openapi'
      preLoaderRoute: typeof ApiPublicV1OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/incidents': {
      id: '/api/public/v1/incidents'
      path: '/api/public/v1/incidents'
      fullPath: '/api/public/v1/incidents'
      preLoaderRoute: typeof ApiPublicV1IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/fleet': {
      id: '/api/public/v1/fleet'
      path: '/api/public/v1/fleet'
      fullPath: '/api/public/v1/fleet'
      preLoaderRoute: typeof ApiPublicV1FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/eta': {
      id: '/api/public/v1/eta'
      path: '/api/public/v1/eta'
      fullPath: '/api/public/v1/eta'
      preLoaderRoute: typeof ApiPublicV1EtaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/credentials': {
      id: '/api/public/v1/credentials'
      path: '/api/public/v1/credentials'
      fullPath: '/api/public/v1/credentials'
      preLoaderRoute: typeof ApiPublicV1CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/courses': {
      id: '/api/public/v1/courses'
      path: '/api/public/v1/courses'
      fullPath: '/api/public/v1/courses'
      preLoaderRoute: typeof ApiPublicV1CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/clinics': {
      id: '/api/public/v1/clinics'
      path: '/api/public/v1/clinics'
      fullPath: '/api/public/v1/clinics'
      preLoaderRoute: typeof ApiPublicV1ClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/share/$token': {
      id: '/api/public/v1/share/$token'
      path: '/api/public/v1/share/$token'
      fullPath: '/api/public/v1/share/$token'
      preLoaderRoute: typeof ApiPublicV1ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/incidents/$id': {
      id: '/api/public/v1/incidents/$id'
      path: '/$id'
      fullPath: '/api/public/v1/incidents/$id'
      preLoaderRoute: typeof ApiPublicV1IncidentsIdRouteImport
      parentRoute: typeof ApiPublicV1IncidentsRoute
    }
    '/api/public/v1/vehicles/$id/work_orders': {
      id: '/api/public/v1/vehicles/$id/work_orders'
      path: '/api/public/v1/vehicles/$id/work_orders'
      fullPath: '/api/public/v1/vehicles/$id/work_orders'
      preLoaderRoute: typeof ApiPublicV1VehiclesIdWork_ordersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/vehicles/$id/defects': {
      id: '/api/public/v1/vehicles/$id/defects'
      path: '/api/public/v1/vehicles/$id/defects'
      fullPath: '/api/public/v1/vehicles/$id/defects'
      preLoaderRoute: typeof ApiPublicV1VehiclesIdDefectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/vehicles/$id/credentials': {
      id: '/api/public/v1/vehicles/$id/credentials'
      path: '/api/public/v1/vehicles/$id/credentials'
      fullPath: '/api/public/v1/vehicles/$id/credentials'
      preLoaderRoute: typeof ApiPublicV1VehiclesIdCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/fleet/$id/location': {
      id: '/api/public/v1/fleet/$id/location'
      path: '/$id/location'
      fullPath: '/api/public/v1/fleet/$id/location'
      preLoaderRoute: typeof ApiPublicV1FleetIdLocationRouteImport
      parentRoute: typeof ApiPublicV1FleetRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCallCenterRoute: typeof AuthenticatedCallCenterRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedDeveloperRoute: typeof AuthenticatedDeveloperRoute
  AuthenticatedDispatchRoute: typeof AuthenticatedDispatchRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRoute
  AuthenticatedPatientRoute: typeof AuthenticatedPatientRoute
  AuthenticatedProviderRoute: typeof AuthenticatedProviderRoute
  AuthenticatedRentalsRoute: typeof AuthenticatedRentalsRoute
  AuthenticatedScreeningRoute: typeof AuthenticatedScreeningRoute
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRoute
  AuthenticatedTripsRoute: typeof AuthenticatedTripsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCallCenterRoute: AuthenticatedCallCenterRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedDeveloperRoute: AuthenticatedDeveloperRoute,
  AuthenticatedDispatchRoute: AuthenticatedDispatchRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRoute,
  AuthenticatedPatientRoute: AuthenticatedPatientRoute,
  AuthenticatedProviderRoute: AuthenticatedProviderRoute,
  AuthenticatedRentalsRoute: AuthenticatedRentalsRoute,
  AuthenticatedScreeningRoute: AuthenticatedScreeningRoute,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRoute,
  AuthenticatedTripsRoute: AuthenticatedTripsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface ApiPublicV1FleetRouteChildren {
  ApiPublicV1FleetIdLocationRoute: typeof ApiPublicV1FleetIdLocationRoute
}

const ApiPublicV1FleetRouteChildren: ApiPublicV1FleetRouteChildren = {
  ApiPublicV1FleetIdLocationRoute: ApiPublicV1FleetIdLocationRoute,
}

const ApiPublicV1FleetRouteWithChildren =
  ApiPublicV1FleetRoute._addFileChildren(ApiPublicV1FleetRouteChildren)

interface ApiPublicV1IncidentsRouteChildren {
  ApiPublicV1IncidentsIdRoute: typeof ApiPublicV1IncidentsIdRoute
}

const ApiPublicV1IncidentsRouteChildren: ApiPublicV1IncidentsRouteChildren = {
  ApiPublicV1IncidentsIdRoute: ApiPublicV1IncidentsIdRoute,
}

const ApiPublicV1IncidentsRouteWithChildren =
  ApiPublicV1IncidentsRoute._addFileChildren(ApiPublicV1IncidentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApiDocsRoute: ApiDocsRoute,
  AuthRoute: AuthRoute,
  ClinicsRoute: ClinicsRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TripTokenRoute: TripTokenRoute,
  ApiPublicV1ClinicsRoute: ApiPublicV1ClinicsRoute,
  ApiPublicV1CoursesRoute: ApiPublicV1CoursesRoute,
  ApiPublicV1CredentialsRoute: ApiPublicV1CredentialsRoute,
  ApiPublicV1EtaRoute: ApiPublicV1EtaRoute,
  ApiPublicV1FleetRoute: ApiPublicV1FleetRouteWithChildren,
  ApiPublicV1IncidentsRoute: ApiPublicV1IncidentsRouteWithChildren,
  ApiPublicV1OpenapiRoute: ApiPublicV1OpenapiRoute,
  ApiPublicV1Screening_ordersRoute: ApiPublicV1Screening_ordersRoute,
  ApiPublicV1Web_intakeRoute: ApiPublicV1Web_intakeRoute,
  ApiPublicV1Work_ordersRoute: ApiPublicV1Work_ordersRoute,
  ApiPublicV1ShareTokenRoute: ApiPublicV1ShareTokenRoute,
  ApiPublicV1VehiclesIdCredentialsRoute: ApiPublicV1VehiclesIdCredentialsRoute,
  ApiPublicV1VehiclesIdDefectsRoute: ApiPublicV1VehiclesIdDefectsRoute,
  ApiPublicV1VehiclesIdWork_ordersRoute: ApiPublicV1VehiclesIdWork_ordersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
