-- M09: service_master extensions per Batch C §4 (skip body_site, sub_category — already present).
ALTER TABLE public.service_master
  ADD COLUMN IF NOT EXISTS nphies_map_payer_ref uuid NULL,
  ADD COLUMN IF NOT EXISTS category text NULL,
  ADD COLUMN IF NOT EXISTS claim_type text NULL,
  ADD COLUMN IF NOT EXISTS is_service_flag boolean NULL,
  ADD COLUMN IF NOT EXISTS visit_type text NULL,
  ADD COLUMN IF NOT EXISTS max_qty_per_episode integer NULL,
  ADD COLUMN IF NOT EXISTS max_qty_per_visit integer NULL,
  ADD COLUMN IF NOT EXISTS max_qty_per_billing integer NULL,
  ADD COLUMN IF NOT EXISTS max_qty_per_policy_year integer NULL,
  ADD COLUMN IF NOT EXISTS repeat_block_window_days integer NULL DEFAULT 14,
  ADD COLUMN IF NOT EXISTS has_report boolean NULL,
  ADD COLUMN IF NOT EXISTS performer_role text NULL,
  ADD COLUMN IF NOT EXISTS ordering_specialty_rule jsonb NULL,
  ADD COLUMN IF NOT EXISTS performing_specialty_rule jsonb NULL,
  ADD COLUMN IF NOT EXISTS pregnancy_rule text NULL,
  ADD COLUMN IF NOT EXISTS age_rule jsonb NULL,
  ADD COLUMN IF NOT EXISTS gender_rule text NULL,
  ADD COLUMN IF NOT EXISTS stat_flag boolean NULL,
  ADD COLUMN IF NOT EXISTS tat_minutes integer NULL,
  ADD COLUMN IF NOT EXISTS approx_perform_minutes integer NULL,
  ADD COLUMN IF NOT EXISTS service_consent_form_id uuid NULL,
  ADD COLUMN IF NOT EXISTS validity_start date NULL,
  ADD COLUMN IF NOT EXISTS validity_end date NULL,
  ADD COLUMN IF NOT EXISTS temporary_unavailable boolean NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS not_available_category text NULL,
  ADD COLUMN IF NOT EXISTS service_block boolean NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tooth_number text NULL,
  ADD COLUMN IF NOT EXISTS cannot_combine_service_ids uuid[] NULL,
  ADD COLUMN IF NOT EXISTS general_comments text NULL;